### ISSUE TITLE
Wrap external tasklist with spring-boot

### ISSUE THREAD

**Issue by jangalinski** [holisticon/camunda-bpm-cloud#2]
I did not manage to run the node.js app. Maybe we should wrap it with jhipster?

**Comment by zambrovski** [comment]
Please no JHipster. But we can run it as a static resource from the container started by the Spring boot.

**Comment by zambrovski** [comment]
Currently, the Maven build runs the Node build and produces a simple static page, which can be packaged into the spring-boot archive. The problem is, that this archive must be the edge service, in order to route the requests to the backend.

**Comment by jangalinski** [comment]
Plan:

* extend cloud-tasklist with spring-boot java app + zuul
* configure zuul to delegate to event service
