### ISSUE TITLE
switch to camunda spring boot 2.1.0

### ISSUE THREAD

**Issue by jangalinski** [holisticon/camunda-bpm-cloud#43]
with 2.1 we will have:

- camunda 7.6
- spring boot 1.5.3

and, most important: a prefixed uuidGenerator ... so we can transport the app Name with the taskId.

**Comment by stefanzilske** [comment]
I can do this at our next workstream day. A good opportunity to get back on track.

**Comment by jangalinski** [comment]
Be forewarned: Last time I tried this with 2.0.0 I had some (can't say which) problems that let to a rollback to 1.3.0. So it might be an easy task to take and and get on board .... but it also might be a nasty hell.
I would try it out and tell you what it will be ... but then the issue would be closed ...

**Comment by jangalinski** [comment]
I used some spare time on the balcony to finally fix this ...
